### ISSUE TITLE
Define sprint milestones.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Owl2#15]

**Comment by yossigil** [comment]
In general, one, or all of you should watch up for all issues of a project and nurture this.

@AdiOmari @zvili @yh-github @orimarco @idabran :  clarify to all teams that the work status is determined by the current issue map.

**Comment by Lidkin5** [comment]
i'm sorry, but i do not understand what is the "definition of done " for this issue. 
all our coding issues milestones are set. 
can you please clarify ?@yossigil

**Comment by yossigil** [comment]
An issue is something that has a start, a task, and a clear crisp definition of when it is DONE. This issue is an umbrella issue. GUI

**Comment by Lidkin5** [comment]
can we close this issue now? @yossigil

**Comment by yossigil** [comment]
An issue can be closed when the task is complete. I can go and check if you completed the task. Do you want me to do so, or would you like to make the decision yourself?

**Comment by Lidkin5** [comment]
All issues have assignee and milestones, all but the karma pages.
All issues defined so that the definition of done is clear.  
What about the karma pages?  should we add milestones (something like  the end of the project ) ? 
Is it OK to close this issue?  @yossigil

**Comment by yossigil** [comment]
Karma pages are special, We need a better mechanism, but we don't.

I went out and checked your milestones. You should have at least one more, for the end of sprint 2, which is as defined in class, your team meetings - for now, keep it for one week before the end of the semester and consult with the team advisor.

**Comment by SapirBismot** [comment]
Done!
