### ISSUE TITLE
Create Model Interface

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Owl2#18]
The model has two jobs: it must both store a state and manage subscribers
Anything which can change (any property) must have a list of listeners which it contacts whenever the value changes. The property listeners allow us to have multiple views on the same data, which are all live-updated when the state changes.

**Comment by OmriBS** [comment]
what exactly do we have to do here? (i understood the theory) which methods do we need to implement? let's split the work

**Comment by OmriBS** [comment]
i'll work on this part

**Comment by nikitadizhur** [comment]
@OmriBS after you will finish the interface itself (or maybe it will become an abstract class), can you, please, add an implementation with methods pickCourse(name), dropCourse(name), getCoursesNames() and getCourseByName(name)?
It hasn't to be exactly the same names for methods, but, please, notify me when you will finish with it.

**Comment by OmriBS** [comment]
Ok

**Comment by OmriBS** [comment]
@nikitadizhur 
It's seems that there is a gap in my knowledge about the model interface and after searching the internet there are subjecs that are still a mystery.
What is the relations between the model interface and the other structures? I've noticed that the Controller interface has a field of type Model which he uses, Is the Model just a representation of the program database? it suppose to connect to our databse file which contains the courses data to the rest of the program?

**Comment by nikitadizhur** [comment]
@OmriBS yes I was also really confused by all this stuff. This is how I understand this:
Model isn't only the data storage, but implements business logic as well (there is not much of it for now).
Model knows nothing about View. Model has list of listeners that it has to notify when it changes its own state (You can create your custom Event by inheriting from ActionEvent). Usually those listeners are views, but it doesn't really matter.
Controller asks Model for data (usually by getters) and sometimes updates it as the result of users' actions.
You can look at CourseListController and CourseSelectionController to see what methods you need to implement in concrete implementation of Model interface. You have to think whether it is enough to create one Model subclass that will satisfy all controllers, or create different Model subclasses for different controllers and maybe put them in some kind of hierarhy (I personally don't really sure what is the right choice).

**Comment by OmriBS** [comment]
@nikitadizhur 
i've finished with the implementation (i'm still not sure what is going on...), and implemented the methods you asked exept pickCourse(name) which i'm not sure what the difference between it and getCourseByName.
(for some reason my commit didn't bound to this issue)

**Comment by nikitadizhur** [comment]
@OmriBS pickCourse - mark course that was picked by user as chosen

**Comment by nikitadizhur** [comment]
@OmriBS purpose of pickCourse isn't loading course to system. it was mean to mark course as chosen one by user (it will become blue in GUI). if user can see this course - that means that you have already loaded it.

I have realized now that my previous declaration of CourseLoader interface was incorrect. I'll update it now, so maybe it will be easier and rather correctly to use. Sorry for mess.
CourseLoader - retrieve data from DB and saves it in there. It is not intended to store data inside itself. But you have to store some data in Model, because you don't want to load it every time.
I think it would be wise to add to CourseLoader some methods that reflect Loader. such as:
getCourse, updateCourse, loadAllCourseNames, etc...
Model checks if it has those courses, and if not - then it tries to load them from Loader.

**Comment by nikitadizhur** [comment]
@OmriBS 
1. Model stores courses that system uses. It's not necessarily available to user.
Model sends only relevant (asked) data to it's listeners, but that doesn't mean that Model throws away all other data.
Loader loads data that Model asked him to load from DB and transfers it to Model. Then Model chose what to do with it.
For example, Model can have some kind of a cache to store previously loaded courses or course names, so it doesn't have to load it again and again from DB with Loader's help.
2. cb - CourseBuilder. I wanted to forbid create Course for anyone except CourseLoader. so this is workaround that prevents any other class in system that is not Loader from creating instances of Course. path - it's path to DB.

**Comment by leyaniv** [comment]
@nikitadizhur @OmriBS 
About loadCourses in CourseLoader.
1. How would call it? Where should we save the returned map. Nikita said that CourseLoader is not intended to store data inside itself. In the future, we might use a SQL database for this shit, but for now, I think we need a temporary place to store all the data on runtime when we load the app.
2. The function takes a list called "names". What is it for? List of courses names? What if we want to load all courses (e.g. when we want to show the user a list of all the courses)? Should the function accept an empty list as a sign to load all the courses?

**Comment by nikitadizhur** [comment]
@leyaniv @OmriBS 
1. Model stores runtime data.
2. But there is a function called loadAllCourses in Loader...
loadCourses(List<String> names) - loads only specified courses and not all the database.
we never want to show all courses with all the details at the same time to user. usually what we want is list of name of all courses. and the we chose one and display the full information about it.

**Comment by alexvitho** [comment]
Done
