### ISSUE TITLE
Create Controller Interface

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Owl2#19]
The GUI parts which do not update when the model changes -- are the responsibility of the controller.
When you try to modify a field in the view, the controller needs to pick up the editing event, process it, and send it to the model; the model will then update the view if/when the value actually changes.
In many frameworks, the controller appears as a collection of methods and listeners built into both the data model and the view.

**Comment by nikitadizhur** [comment]
waiting for views and models to be implemented

**Comment by OmriBS** [comment]
@nikitadizhur , i refactor view as an observer instead of actionListner and it affected the implemenation of the controller and now its needs changes which i'm not sure how you would like to fix (sorry for the work)

**Comment by alexvitho** [comment]
done
