### ISSUE TITLE
Choose a name to the project

### ISSUE THREAD

**Issue by Lidkin5** [TechnionYP5777/Owl2#26]
We need to choose a name to the project. some suggestions that came up: 
hUmonGous,    Plan T,     TechPlan,    StudyTime,   PlanEasy,    S-hour,    Plan&Go.
maybe something with owls (Borises project called O.W.L)...

**Comment by yossigil** [comment]
In general it is not a good idea to have so many names for an issue. It means no one takes personal responsibility. I would recommend assigning the task of collecting names to one and only one team member. Others can make offers, but he is the one who has to make the list.

**Comment by leyaniv** [comment]
Current suggestions: UGH!, SLizard, Sleazy, Sluzy.

**Comment by SapirBismot** [comment]
what about Up&Go ?

**Comment by kobybs** [comment]
decided about Up&Go. @zvili

**Comment by zvili** [comment]
@kobybs 
So, if I understand correctly you want me to rename your repository from:Owl2 to:Up&Go.
Please ack.

**Comment by kobybs** [comment]
@zvili that's correct.
Thank you.

**Comment by zvili** [comment]
"&" character is not accepted as part of the repository name,
May I suggest the name: UpAndGo

**Comment by kobybs** [comment]
That's great. Thanks.
