### ISSUE TITLE
Getting to agreement on how the hell does MVC work

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Owl2#29]
I'm not completely understand MVC, as you saw, but we have to start doing things.
So, there are guidelines on how I believe it works:
- The view listens to the model for change events. Whenever it gets one it updates itself to display the latest model data
- The view fires an event to all registered listeners when the user performs an action
- The controller listens to the view for action events. Whenever it gets one it changes the model state accordingly.
- The model does not listen to anything. Whenever its state is changed, it fires a change event to all registered listeners.

As to say:
- Views updating models is wrong
- Controllers updating views is wrong
- Controllers listening to models is wrong
- Models listening to anything else is wrong

And often something outside these three hooks the three together.

E.g., if user wants to see list of course-names and view doesn't have it:
1. view fire event to controller.
2. controller changes the model.
3. after the change model fire event to view about it.
and so on and so forth.

I would really appreciate if all of you guys can say something about it in comments (agree/disagree/throw at me some tomatoes), because this subject really drive me nuts.

@OmriBS @Lidkin5 @alexvitho @leyaniv @SapirBismot @kobybs

**Comment by OmriBS** [comment]
I don't like tomatoes... :)
i think that the most importent question that we need to ask ourselves right now is - is this model is a MUST for the presantation on the 13.12.
we must remember that the goal is *usable* prototype so if we can present the initial program without complicating stuff its for the better, and after the presantation we can ask yosi or yoav to help us with understanding the idea of MVC.

**Comment by leyaniv** [comment]
I'm all for not over complicating stuff for the time being. If we need to break some laws of the model to have something working for the presentation, so we should break it. Nikita, I really appreciate the amount of effort you put into doing stuff according to this model, but I'm also finding it hard to understand the benefits it has for us at this stage of the project.

**Comment by nikitadizhur** [comment]
@OmriBS @leyaniv okey, you kinda right. maybe it isn't the time and the place for MVC.
so what if we do next: View receives Model as argument and do what it has to do for display the asked data.

**Comment by alexvitho** [comment]
@nikitadizhur  I think this is a good idea (View receives Model as argument ), it will be much more simple for now.

**Comment by alexvitho** [comment]
done
