### ISSUE TITLE
add method saveChosenCourseNames to CourseLoader

### ISSUE THREAD

**Issue by Lidkin5** [TechnionYP5777/Owl2#34]

**Comment by leyaniv** [comment]
@Lidkin5 
Should we save only the names?
Maybe it is best to save the id because it is guaranteed to be unique .

**Comment by Lidkin5** [comment]
@leyaniv  
I think  the id is better, but it is also a string so it is just a name convention .

**Comment by leyaniv** [comment]
@Lidkin5 
Yeah you are right. Let keep it called name for now. We just need to keep it constant with the function that loads the chosed courses from the xml.

**Comment by leyaniv** [comment]
done
