### ISSUE TITLE
Model always initializing empty list

### ISSUE THREAD

**Issue by alexvitho** [TechnionYP5777/Owl2#42]
in model.java 

	protected List<Course> courseList;
	protected List<Course> pickedCourseList;
	protected List<Observer> listenersList;
	protected CourseLoader loader;
	
	public Model(CourseLoader loader){
		this.courseList = new ArrayList<>();
		this.pickedCourseList = new ArrayList<>();
		this.listenersList = new ArrayList<>();
		this.loader = loader;
	}

the 
public List<String> getCoursesNames() {
		List<String> $ = new ArrayList<>();
		for(Course it:courseList)
			$.add(it.getName());
		return $;
	}
function returns empty list. 
fix it please, or i do not understand something?.

**Comment by nikitadizhur** [comment]
@alexvitho I'll fix it, but I don't understand why it prevents you from continuing your task.

**Comment by alexvitho** [comment]
we can pull the list from the loader inside the mode, but not from the model itself which is the correct way, no? @nikitadizhur

**Comment by nikitadizhur** [comment]
pull it from the model.
why it stops you from continuing?

**Comment by alexvitho** [comment]
never mind, just notify us when you will fix it, we will simulate a list for now.

**Comment by nikitadizhur** [comment]
@alexvitho fixed
